#VERSION 100
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_Max
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_Max
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#1
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_S71500-ET200MP station_1
CONNECTEDTO_SIGNAL=s_vq1Fbk
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#1
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#1
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_Signed2Unsigned#1
CONNECTEDTO_SIGNAL=s_X
ASSIGNEDTO_SOURCE=s_Phys2Raw#1
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#1
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_Unsigned2Signed#2
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Raw2Phys#1
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#1
SIGNAL=s_Phys_Lower_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#1
SIGNAL=s_Phys_Upper_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#1
SIGNAL=s_Phys_Lower_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#1
SIGNAL=s_Raw_Lower_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#1
SIGNAL=s_X
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_ChartName#2
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Phys2Raw#1
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#1
SIGNAL=s_Raw_Upper_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#1
SIGNAL=s_Raw_Upper_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_zTimeParamFault
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_zLimitParamFault
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_z
INFO {
TYPE=i_1060865
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_zOpen
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_zClose
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_zValue
INFO {
TYPE=i_1060865
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#4
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_Phys2Raw#4
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#4
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#4
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_S71500-ET200MP station_1
CONNECTEDTO_SIGNAL=s_vq2SP
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#4
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#4
SIGNAL=s_Raw_Lower_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#4
SIGNAL=s_Raw_Upper_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_Value
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_Raw2Phys#2
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_Value
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_T_Open
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_T_Open
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_T_Close
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_T_Close
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_MAN
INFO {
TYPE=i_1049604
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_MAN
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_Setpoint
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_Setpoint
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_HIHI
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_HIHI
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_zClose
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_z
INFO {
TYPE=i_1060865
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_zTimeParamFault
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_zOpen
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_zLimitParamFault
INFO {
TYPE=i_1060868
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_zValue
INFO {
TYPE=i_1060865
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_q2
INFO {
TYPE=i_1050625
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_q2
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_q1
INFO {
TYPE=i_1050625
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_q1
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_Min
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_Min
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_T_Open
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_T_Open
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_Value
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_Raw2Phys#1
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_Value
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_T_Close
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_T_Close
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_Setpoint
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_Setpoint
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_MAN
INFO {
TYPE=i_1049604
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_MAN
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_Y
INFO {
TYPE=i_1050625
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#2
SIGNAL=s_X
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_ChartName#3
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Phys2Raw#2
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#2
SIGNAL=s_Raw_Upper_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#2
SIGNAL=s_Raw_Lower_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#2
SIGNAL=s_Phys_Lower_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#2
SIGNAL=s_Phys_Upper_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Unsigned2Signed#3
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_Raw2Phys#2
CONNECTEDTO_SIGNAL=s_X
ASSIGNEDTO_SOURCE=s_Unsigned2Signed#3
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn
SIGNAL=s_X
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
ASSIGNEDTO_SOURCE=s_hladinaIn
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_Signed2Unsigned#3
CONNECTEDTO_SIGNAL=s_X
ASSIGNEDTO_SOURCE=s_hladinaIn
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn#1
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_Signed2Unsigned#5
CONNECTEDTO_SIGNAL=s_X
ASSIGNEDTO_SOURCE=s_hladinaIn#1
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn#1
SIGNAL=s_Phys_Lower_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn#1
SIGNAL=s_X
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
ASSIGNEDTO_SOURCE=s_hladinaIn#1
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn#1
SIGNAL=s_Phys_Upper_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_Unsigned2Signed#3
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_S71500-ET200MP station_1
CONNECTEDTO_SIGNAL=s_vq2Out
ASSIGNEDTO_SOURCE=s_Unsigned2Signed#3
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#2
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_Phys2Raw#2
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#2
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#2
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_S71500-ET200MP station_1
CONNECTEDTO_SIGNAL=s_vq2Fbk
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#2
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#2
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_Signed2Unsigned#2
CONNECTEDTO_SIGNAL=s_X
ASSIGNEDTO_SOURCE=s_Phys2Raw#2
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#2
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_Unsigned2Signed#3
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Raw2Phys#2
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#2
SIGNAL=s_Y
INFO {
TYPE=i_1050625
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_ChartName#3
CONNECTEDTO_SIGNAL=s_Value
ASSIGNEDTO_SOURCE=s_Raw2Phys#2
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_LOLO
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_LOLO
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Unsigned2Signed#2
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_S71500-ET200MP station_1
CONNECTEDTO_SIGNAL=s_vq1Out
ASSIGNEDTO_SOURCE=s_Unsigned2Signed#2
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#1
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_Phys2Raw#1
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#1
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#1
SIGNAL=s_Y
INFO {
TYPE=i_1050625
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_ChartName#2
CONNECTEDTO_SIGNAL=s_Value
ASSIGNEDTO_SOURCE=s_Raw2Phys#1
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_LO
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_LO
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Unsigned2Signed#2
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_Raw2Phys#1
CONNECTEDTO_SIGNAL=s_X
ASSIGNEDTO_SOURCE=s_Unsigned2Signed#2
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#2
SIGNAL=s_Phys_Lower_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#2
SIGNAL=s_Phys_Upper_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#4
SIGNAL=s_Phys_Lower_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#4
SIGNAL=s_Phys_Upper_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_HI
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_HI
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_LO
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_LO
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I20.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I20.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I20.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I21.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I21.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I21.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_hladina
INFO {
TYPE=i_2098178
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_3
SIMATICHINT=s_IW14
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_hladina
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
INFO {
TYPE=i_2098178
CONTEXT=i_3
CONNECTED=True
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_hladina
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_vq1Fbk
INFO {
TYPE=i_2098178
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_3
SIMATICHINT=s_IW10
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq1Fbk
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
INFO {
TYPE=i_2098178
CONTEXT=i_3
CONNECTED=True
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq1Fbk
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_vq1Out
INFO {
TYPE=i_2099202
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_3
SIMATICHINT=s_QW0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq1Out
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
INFO {
TYPE=i_2099202
CONTEXT=i_3
CONNECTED=False
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq1Out
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_vq2Fbk
INFO {
TYPE=i_2098178
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_3
SIMATICHINT=s_IW12
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq2Fbk
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
INFO {
TYPE=i_2098178
CONTEXT=i_3
CONNECTED=True
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq2Fbk
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_vq2Out
INFO {
TYPE=i_2099202
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_3
SIMATICHINT=s_QW2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq2Out
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
INFO {
TYPE=i_2099202
CONTEXT=i_3
CONNECTED=False
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq2Out
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_vq2SP
INFO {
TYPE=i_2098178
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_3
SIMATICHINT=s_IW16
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq2SP
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
INFO {
TYPE=i_2098178
CONTEXT=i_3
CONNECTED=True
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_vq2SP
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#1
SIGNAL=s_Raw_Lower_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_HI
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_HI
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_LOLO
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_LOLO
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_ChartName#3
SIGNAL=s_Y
INFO {
TYPE=i_1050625
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#3
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn#1
SIGNAL=s_Raw_Lower_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn#1
SIGNAL=s_Raw_Upper_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#2
SIGNAL=s_Raw_Lower_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Raw2Phys#2
SIGNAL=s_Raw_Upper_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_Raw2Phys#1
SIGNAL=s_Phys_Upper_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_ChartName#2
SIGNAL=s_HIHI
INFO {
TYPE=i_1050628
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_ChartName#2
ASSIGNEDTO_SIGNAL=s_HIHI
OCCURER=s_proj\Pristroje\Ventil\vq1.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#4
SIGNAL=s_X
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
ASSIGNEDTO_SOURCE=s_Phys2Raw#4
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_Phys2Raw#4
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_Signed2Unsigned#4
CONNECTEDTO_SIGNAL=s_X
ASSIGNEDTO_SOURCE=s_Phys2Raw#4
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Ventil\vq2.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I22.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I22.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I22.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I23.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I23.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I23.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I24.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I24.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I24.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I25.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I25.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I25.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_hladinaSP
INFO {
TYPE=i_2098178
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_3
SIMATICHINT=s_IW18
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_hladinaSP
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
INFO {
TYPE=i_2098178
CONTEXT=i_3
CONNECTED=True
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_hladinaSP
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I8.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I8.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I8.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.0
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.0
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.0
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.1
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.1
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.1
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.2
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.2
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.2
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.3
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.3
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.3
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.4
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.4
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.4
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.5
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.5
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.5
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.6
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.6
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.6
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_S71500-ET200MP station_1
SIGNAL=s_I9.7
INFO {
TYPE=i_2098180
CONTEXT=i_2
CONNECTED=False
SIMATICTYPE=i_0
SIMATICHINT=s_I9.7
ASSIGNEDTO_SOURCE=s_S71500-ET200MP station_1
ASSIGNEDTO_SIGNAL=s_I9.7
OCCURER=s_io\PLCSIMAdvancedROOT\PLCSIMAdvanced1\gateway.gate
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#5
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_hladinaIn#1
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#5
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#5
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_S71500-ET200MP station_1
CONNECTEDTO_SIGNAL=s_hladinaSP
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#5
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn
SIGNAL=s_Raw_Lower_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn
SIGNAL=s_Raw_Upper_Limit
INFO {
TYPE=i_1064962
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#3
SIGNAL=s_X
INFO {
TYPE=i_1049602
CONTEXT=i_1
CONNECTED=True
CONNECTEDTO_SOURCE=s_hladinaIn
CONNECTEDTO_SIGNAL=s_Y
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#3
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_Signed2Unsigned#3
SIGNAL=s_Y
INFO {
TYPE=i_1050626
CONTEXT=i_1
CONNECTED=False
CONNECTEDTO_SOURCE=s_S71500-ET200MP station_1
CONNECTEDTO_SIGNAL=s_hladina
ASSIGNEDTO_SOURCE=s_Signed2Unsigned#3
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn
SIGNAL=s_Phys_Lower_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_hladinaIn
SIGNAL=s_Phys_Upper_Limit
INFO {
TYPE=i_1064961
CONTEXT=i_1
CONNECTED=False
OCCURER=s_proj\Pristroje\Analog\hladina.diag
}
}
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_h0
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_h0
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_h
INFO {
TYPE=i_1050625
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_h
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_Slider#1
SIGNAL=s_X
INFO {
TYPE=i_4195329
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_Slider#1
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_Slider#1
SIGNAL=s_Y
INFO {
TYPE=i_4196353
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_Slider#1
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_Slider#2
SIGNAL=s_X
INFO {
TYPE=i_4195329
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_Slider#2
ASSIGNEDTO_SIGNAL=s_X
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_Slider#2
SIGNAL=s_Y
INFO {
TYPE=i_4196353
CONTEXT=i_1
CONNECTED=False
ASSIGNEDTO_SOURCE=s_Slider#2
ASSIGNEDTO_SIGNAL=s_Y
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_V1
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_V1
OCCURER=s_proj\Simulace.diag
}
}
SIGNAL {
SOURCE=s_HladninaNadrze#1
SIGNAL=s_V2
INFO {
TYPE=i_1049601
CONTEXT=i_1
CONNECTED=True
ASSIGNEDTO_SOURCE=s_HladninaNadrze#1
ASSIGNEDTO_SIGNAL=s_V2
OCCURER=s_proj\Simulace.diag
}
}
